run-dist: # запуск исполняемого файла
	@./build/install/app/bin/app

run: # короткий вариант запуска исполняемого файла
	@./build/install/app/bin/app

.PHONY: build

build: # сборка проекта
	./gradlew build
